// <auto-generated />
namespace PatientApplication.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddPhysician : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddPhysician));
        
        string IMigrationMetadata.Id
        {
            get { return "201904180352093_AddPhysician"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
